image: docker:stable-dind

stages:
  - build

variables:
  IMAGE_NAME: "yw4code/cluster-tool"

build_image_job:
  stage: build
  script:
    - docker version
    - docker build -t "$IMAGE_NAME:latest" .