image: docker:18.09.7-dind
services:
  - docker:18.09.7-dind
variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay
  IMAGE_NAME: "harbor.hw.codes/ares/cluster-tool"

stages:
  - build

before_script:
  - docker info
  - echo "$DOCKER_PASSWORD"| docker login harbor.hw.codes --username 'robot$builder' --password-stdin


build_dev_image_job:
  stage: build
  only:
    - dev
  script:
    - docker version
    - docker build -t "$IMAGE_NAME:latest" .
    - docker image push "$IMAGE_NAME:latest"


build_tag_image_job:
  stage: build
  only:
    - /^UAT.*$/
    - /^PROD.*$/
  script:
    - docker version
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_TAG" .
    - docker image push "$IMAGE_NAME:$CI_COMMIT_TAG"


# deploy_job:
#   stage: deploy
#   image: harbor.hw.codes/sre/deploy-tool
#   script:

# deploy_helm_package_agent:
#   stage: deploy
#   image: docker pull traherom/kustomize-docker:2.0.0
#   tags:
#     - docker
#   only:
#     - dev
#   environment:
#     name: dev
#     url: https://your-domain.com
#   script: