image: docker:18.09.7-dind
services:
  - docker:18.09.7-dind
variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay
  IMAGE_NAME: "harbor.hw.codes/sre/cluster-tool"

  # setup following variables on Setting/CICD page
  # DOCKER_PASSWORD

stages:
  - build

before_script:
  - docker info
  - echo "$DOCKER_PASSWORD"| docker login harbor.hw.codes --username 'robot$builder' --password-stdin


build_image_job:
  stage: build
  script:
    # - export DOCKER_HOST="tcp://localhost:2375"
    - docker version
    - docker build -t "$IMAGE_NAME:latest" .
    - docker image push "$IMAGE_NAME:latest"

