image: docker:19.03.1
services:
- docker:19.03.1-dind

stages:
  - build

variables:
  IMAGE_NAME: "yw4code/cluster-tool"
  DOCKER_HOST: tcp://docker:2375

build_image_job:
  stage: build
  image: google/cloud-sdk
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker version
    - docker build -t "$IMAGE_NAME:latest" .