image: docker:git
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay



stages:
  - build

variables:
  IMAGE_NAME: "yw4code/cluster-tool"

build_image_job:
  stage: build
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker version
    - docker build -t "$IMAGE_NAME:latest" .